---
title: "Data Science 310: Data summarization and visualization"
author: Fall 2017
---


### [Office hours](Schedule.html)
### Announcements

* Exam on Friday, 10/13.


### [Midterm project](Midterm.html)

Presentations to begin 10/37. 

### Notes

1. [Principles of data visualization](https://www.dropbox.com/s/awpa7c916y6li13/1%20-%20Principles%20of%20data%20visualization.pptx?dl=0)
2. [Intro to Tableau](https://www.dropbox.com/s/e8yp85lamhq1gwr/2%20-%20Intro%20to%20Tableau-F17.docx?dl=0)
3. [Univariate visualizations](https://www.dropbox.com/s/7jy0mpimp94gyj0/3%20-%20Univariate%20visualizations-F17.docx?dl=0)
4. [Multivariate visualizations](https://www.dropbox.com/s/68aul6yh1im6mt8/4%20-%20Multivariate%20visualizations%20-%20F17.docx?dl=0)
5. [3-way scatterplots and maps](https://www.dropbox.com/s/ooqwo2ml7i3mctx/5%20-%20three-way%20scatterplots%20and%20maps%20-%20F17.docx?dl=0)
6. [Interactive Dashboards](https://www.dropbox.com/s/jz98g08jnkhvzli/6%20-%20Interactive%20dashboards%20-%20F17.docx?dl=0)
7. [Data visualization in R with ggplot2](Intro_to_ggplot2.html)

### Resources

* Additional courses on R provided by [Data Camp](https://www.datacamp.com/)
* [CrowdGrader instructional video](https://mediaspace.mnscu.edu/media/CrowdGrader+Instructions/0_6sfxk3a6)
* [Dr. Tom Grier's visual communication notes](https://www.dropbox.com/s/kumcs4y9tfoxjl7/VisCom-Composition-EyeBrain%20%28002%29.ppt?dl=0)
* [Slides for Dr. Eastman's critiques](https://www.dropbox.com/s/bvbdjkhzgtwk628/Images_For_Eastman.pptx?dl=0)

### Critiques 

* [Critique #1 (due Wednesday, 8/30 by 11:59pm)](Critique1.html) | [Discussion slides](https://www.dropbox.com/s/t911qfc8uihftzg/DT1-comments-F17.pptx?dl=0)
* [Critique #2 (due Sunday 10/8 by 11:59pm)](Critique2.html)
* [Practice critique of Design Task 3 submissions, using the midterm rubric](https://www.dropbox.com/s/rfqx5zjdqxday2x/DT3-comments-F17.pptx?dl=0)

### Design tasks 

* [Design Task 1](https://www.dropbox.com/s/14k8e9ncl7ydxat/DT1-F17.docx?dl=0) | First draft to CrowdGrader: 9/3 ([link to CrowdGrader assignment](https://www.crowdgrader.org/crowdgrader/venues/join/3338/wyseba_dytybo_dynumi_cywyro)) | Critiques due: 9/7 | Final draft to D2L: 9/10
    - [Comments/Critiques ppt](https://www.dropbox.com/s/rmcquke12hnbe4o/Bacteria-comments-F17.pptx?dl=0) | [My design](https://www.dropbox.com/s/odnpm4t5kdjl15n/Bacteria_Sigmoid_Final.twbx?dl=0) | [My design how-to](https://www.dropbox.com/s/68ahri9xnnabce4/Bacteria-sigmoid-howto.docx?dl=0)
* [Design Task 2](https://www.dropbox.com/s/qh9t5ac9du0b50t/DT2-F17.docx?dl=0) | First draft to CrowdGrader: 9/15 (midnight) ([link to CrowdGrader assignment](https://www.crowdgrader.org/crowdgrader/venues/join/3350/nycysa_nupugi_mosety_bufasi)) | Critiques due: 9/18 (noon) | Final draft to D2L: 9/20 (midnight)
    - In-class critiques: at each table, assess one of the visualizations below. Answer the following:
        1. For each design task question: A. Is it answered; B. How is it answered (what comparisons must be made to answer the question)?
        2. What is clearly communicated?  What information is difficult to extract?
        3. Look at legends/labels/annotations.  What is effective?  What shows room for improvement?
    - [Example 1](https://www.dropbox.com/s/khmg1mktvsdu4bb/DT2-F17-Example1.twbx?dl=0) | [Example 2](https://www.dropbox.com/s/docbpkhaf1q20hs/DT2-F17-Example2.twbx?dl=0) |  [Example 3](https://www.dropbox.com/s/0497cxeaplw99j9/DT2-F17-Example3.twbx?dl=0) |  [Example 4](https://www.dropbox.com/s/pdy441zgkmi1pvq/DT2-F17-Example4.twbx?dl=0) |  [Example 5](https://www.dropbox.com/s/jdqzls09dw7zs4y/DT2-F17-Example5.twbx?dl=0) | [Example 6](https://www.dropbox.com/s/97t30jyy1wvnaxz/DT2-F17-Example6.twbx?dl=0) |  [Example 7](https://www.dropbox.com/s/15ikjvjrra5pjqp/DT2-F17-Example7.twbx?dl=0) | [Example 8](https://www.dropbox.com/s/vtiu1g106qs13zg/DT2-F17-Example8.twbx?dl=0) | [Example 9](https://www.dropbox.com/s/gkmypt2si0nmage/DT2-F17-Example9.twbx?dl=0) | [Example 10](https://www.dropbox.com/s/i10tx0rm2t56md0/DT2-F17-Example10.twbx?dl=0) | [Example 11](https://www.dropbox.com/s/sa919ast913vdpi/DT2-F17-Example11.twbx?dl=0)
* [Design Task 3](https://www.dropbox.com/s/nhp1fsauhgfpj72/DT3-F17.docx?dl=0) | First draft to CrowdGrader: 9/27 (midnight) | Critiques due: 10/1 (midnight) | Final draft to D2L: 10/4 (midnight)
    - Consider the following example submissions  for Design Task 3.  Assess them according to the [midterm rubric](https://www.dropbox.com/s/7h03rx03aqfuibz/GroupProjectRubric-Fall2017.docx?dl=0)
    - [Static images](https://www.dropbox.com/s/rfqx5zjdqxday2x/DT3-comments-F17.pptx?dl=0)
    - [Example 1](https://www.dropbox.com/s/jvubikaztfs0upu/DT3-F17-Example1.twbx?dl=0) | [Example 2](https://www.dropbox.com/s/lu1mgmrpiegg4ov/DT3-F17-Example2.twbx?dl=0) | [Example 3](https://www.dropbox.com/s/x7iwemlhbs2eyok/DT3-F17-Example3.twbx?dl=0) | [Example 4](https://www.dropbox.com/s/jf6lj6sqvmgwinc/DT3-F17-Example4.twbx?dl=0) | [Example 5](https://www.dropbox.com/s/i82dks79zkm0hnt/DT3-F17-Example5.twbx?dl=0) | [Example 6](https://www.dropbox.com/s/i82dks79zkm0hnt/DT3-F17-Example5.twbx?dl=0) | [Example 7](https://www.dropbox.com/s/sk694bgby8um9dj/DT3-F17-Example7.twbx?dl=0)


### Play days!

* [Play day 1](PlayDay1.html), begins 9/13
* [Play day 2](IPUMS-visualization-ggplot.html) | [R code for plots](IPUMS-visualization-KEY.html)

### Data
* [Burtin's bacteria data](https://www.dropbox.com/s/y3uyg808m0y0zii/Bacteria.csv?dl=0)
* [CDC teenage fertility rate data](https://www.dropbox.com/s/9kb7zxe9p2jb24c/CDC-Teenage-fertility-data-imputed.csv?dl=0)
* [IPUMS-Sex-Age](https://www.dropbox.com/s/ftid3df9962i2il/IPUMS-Sex-Age.csv?dl=0)
* [IPUMS-Sex-EdAttain](https://www.dropbox.com/s/tojah0h83cmypnd/IPUMS-Sex-EdAttain.csv?dl=0)
* [Vox data](https://www.dropbox.com/s/tvoeu4dwsgzmg75/Vox.csv?dl=0)
* [World bank regions](https://www.dropbox.com/s/0m28op23nou0xaj/worldbankregions.csv?dl=0)
* [World bank indicators](https://www.dropbox.com/s/dqp1wlha7h578fp/WorldBank-clean.csv?dl=0)

